server:
  port: 8085

spring:
  application:
    name: reporting-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/reporting_db}
    username: ${SPRING_DATASOURCE_USERNAME:reporting_user}
    password: ${SPRING_DATASOURCE_PASSWORD:reporting_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:heartsync}
    password: ${RABBITMQ_PASSWORD:heartsync_pass}

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minio_admin}
  secret-key: ${MINIO_SECRET_KEY:minio_pass}
  bucket: clinical-reports

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
